{{- $namespace := .Values.global.infrastructureNamespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "social-media-feed-backend-charts.fullname" . }}
  labels:
    {{- include "social-media-feed-backend-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "social-media-feed-backend-charts.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: {{ $namespace }}
spec:
  clusterIP: None
  selector:
    database: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.global.postgresPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: {{ $namespace }}
spec:
  selector:
    database: redis
  ports:
    - protocol: TCP
      port: {{ .Values.global.redisPort }}
---