
version: '3.7'

networks:
  social_media_feed:
    driver: bridge

services:
  # Generates cluster id and stores it in ./clusterID
  generate-kafka-cluster-id:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    hostname: generate-kafka-cluster-id
    container_name: generate-kafka-cluster-id
    user: root
    volumes:
      - ./scripts/generate-cluster-id.sh:/tmp/generate-cluster-id.sh
      - ./clusterID:/tmp/clusterID
    command: "bash -c '/tmp/generate-cluster-id.sh'"
  kafka-broker-1:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: BROKER://kafka-broker-1:9092,EXTERNAL://kafka-broker-1:39094,CONTROLLER://kafka-broker-1:9093,LOCALHOST://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-broker-1:9092,EXTERNAL://kafka-broker-1:39094,LOCALHOST://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT,LOCALHOST:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093'
      CLUSTER_ID: f1p7ULGbT_qGDINRRLoz7g
  kafka-broker-2:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: BROKER://kafka-broker-2:9092,EXTERNAL://kafka-broker-2:39094,CONTROLLER://kafka-broker-2:9093,LOCALHOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-broker-2:9092,EXTERNAL://kafka-broker-2:39094,LOCALHOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT,LOCALHOST:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093'
      CLUSTER_ID: f1p7ULGbT_qGDINRRLoz7g
  kafka-broker-3:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    ports:
      - "39092:39092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: BROKER://kafka-broker-3:9092,EXTERNAL://kafka-broker-3:39094,CONTROLLER://kafka-broker-3:9093,LOCALHOST://0.0.0.0:39092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-broker-3:9092,EXTERNAL://kafka-broker-3:39094,LOCALHOST://localhost:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT,LOCALHOST:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093'
      CLUSTER_ID: f1p7ULGbT_qGDINRRLoz7g
  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    platform: linux/amd64
    hostname: schema-registry
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
      SCHEMA_REGISTRY_DEBUG: 'true'
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    platform: linux/amd64
    hostname: kafka-ui
    ports:
      - "9000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
      KAFKA_CLUSTERS_0_SCHEMA_REGISTRY: http://schema-registry:8081
  debezium:
    image: debezium/connect:2.5
    platform: linux/amd64
    ports:
      - "8083:8083"
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
      - schema-registry
      - postgres-cdc
    volumes:
      - "./debezium-dependencies:/kafka/connect/debezium-connector-schemaregistry"
    environment:
      # General config
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: "connect-config"
      OFFSET_STORAGE_TOPIC: "connect-offsets"
      STATUS_STORAGE_TOPIC: "connect-status"
      BOOTSTRAP_SERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
      LOGGING_LEVEL: "DEBUG"
      CONNECT_SCHEMA_NAME_ADJUSTMENT_MODE: avro
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  postgres-cdc:
    image: debezium/postgres:16
    platform: linux/amd64
    container_name: postgres-cdc
    hostname: postgres-cdc
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
  redis:
    image: redis:7.2
    platform: linux/amd64
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: admin