
version: '3.7'

networks:
  social_media_feed:
    driver: bridge

services:
  jenkins:
    image: jenkins/jenkins:latest-jdk17
    hostname: jenkins
    ports:
      - "9090:8080"
    volumes:
      - ./jenkins-data:/var/jenkins_home
    environment:
      JENKINS_PORT: 9090
       