# Default values for social-media-feed-backend-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Global values for other child helm charts
global:
  infrastructureConfigMapName: infrastructure-configmap
  infrastructureNamespace: default
  microservicesNamespace: default
  postgresImage: debezium/postgres:16
  redisImage: redis:7.2
  postgresPort: 5432
  redisPort: 6379

# Values only for the umbrella chart

# Defines config map values at ./infrastructureConfigmap.yaml
infrastructureConfigMapData:
    # Kafka bootstrap server is composed of {pod-name}.{service-name}.{namespace}.svc.cluster.local:{port}
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: kafka-broker-0.kafka-broker-service.default.svc.cluster.local:9092,kafka-broker-1.kafka-broker-service.default.svc.cluster.local:9092,kafka-broker-2.kafka-broker-service.default.svc.cluster.local:9092
    - name: EUREKA_HOST
      value: http://eureka-service
    - name: SCHEMA_REGISTRY_HOST
      value: http://schema-registry-service:8081


image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
