{{ $namespace := .Values.global.microservicesNamespace }}
---
{{ with .Values }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service-deployment
  namespace: {{ $namespace }}
spec:
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
        - name: feed-service-container
          image: {{ .podImage }}
          ports:
            - containerPort: {{ .servicePort }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .global.infrastructureConfigMapName }}
                  key: EUREKA_HOST
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: {{ .global.infrastructureConfigMapName }}
                  key: KAFKA_BOOTSTRAP_SERVERS
---
apiVersion: v1
kind: Service
metadata:
  name: feed-service
  namespace: {{ $namespace }}
spec:
  selector:
    app: feed-service
  ports:
    - protocol: TCP
      port: {{ .servicePort }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: feed-postgres
  namespace: {{ $namespace }}
spec:
  serviceName: postgres-headless
  selector:
    matchLabels:
      app: feed-postgres
  template:
    metadata:
      labels:
        app: feed-postgres
        database: postgres
    spec:
      containers:
        - name: feed-postgres-container
          image: {{ .global.postgresImage }}
          ports:
            - containerPort: {{ .global.postgresPort }}
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: admin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: feed-redis
  namespace: {{ $namespace }}
spec:
  serviceName: redis-headless
  selector:
    matchLabels:
      app: feed-redis
  template:
    metadata:
      labels:
        app: feed-redis
        database: redis
    spec:
      containers:
        - name: feed-redis-container
          image: {{ .global.redisImage }}
          ports:
            - containerPort: {{ .global.redisPort }}
          env:
            - name: REDIS_PASSWORD
              value: admin
---
{{- end }}