---
{{- $namespace := .Values.global.infrastructureNamespace }}
{{- with .Values.eurekaService }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service-deployment
  namespace: {{ $namespace }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service-container
          image: {{ .image }}
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: {{ $namespace }}
spec:
  selector:
    app: eureka-service
  ports:
    - protocol: TCP
      port: {{ .port }}
    {{ end }}
---
{{- with .Values.apiGatewayService }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service-deployment
  namespace: {{ $namespace }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service-container
          image: {{ .image }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: {{ $namespace }}
spec:
  selector:
    app: api-gateway-service
  ports:
    - protocol: TCP
      port: {{ .port }}
{{- end }}
---
{{- with .Values.kafka }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
  namespace: {{ $namespace }}
spec:
  replicas: {{ .replicas }}
  serviceName: kafka-broker-service
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
        - name: kafka-broker-container
          image: {{ .image }}
          ports:
            - containerPort: {{ .port }}
          command: ["sh", "-exc"]
          args: ["export KAFKA_NODE_ID=${HOSTNAME##*-} &&
          export KAFKA_ADVERTISED_LISTENERS=BROKER://${POD_NAME}.kafka-broker-service.${POD_NAMESPACE}.svc.cluster.local:9092 &&
          export KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka-broker-0.kafka-broker-service.${POD_NAMESPACE}.svc.cluster.local:9093,1@kafka-broker-1.kafka-broker-service.${POD_NAMESPACE}.svc.cluster.local:9093,2@kafka-broker-2.kafka-broker-service.${POD_NAMESPACE}.svc.cluster.local:9093 &&

          exec /etc/confluent/docker/run
          "]
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              value: {{ $namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-service
  namespace: {{ $namespace }}
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-kafka-int
      port: {{ .port }}
      protocol: TCP
      targetPort: tcp-kafka-int
    - name: tcp-kafka-ctrl
      port: 9093
      protocol: TCP
      targetPort: tcp-kafka-ctrl
  selector:
    app: kafka-broker
  sessionAffinity: None
  type: ClusterIP
  {{- end }}
---
{{- with .Values.schemaRegistry }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: schema-registry-deployment
  namespace: {{ $namespace }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry-container
          image: {{ .image }}
          ports:
            - containerPort: {{ .port }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end}}
            - name: POD_NAMESPACE
              value: {{ $namespace }}
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.infrastructureConfigMapName }}
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_CLUSTERS_0_SCHEMA_REGISTRY
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.infrastructureConfigMapName }}
                  key: SCHEMA_REGISTRY_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
  namespace: {{ $namespace }}
spec:
  selector:
    app: schema-registry
  ports:
    - protocol: TCP
      port: {{ .port }}
      {{- end }}
---
{{- with .Values.debezium }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: debezium-deployment
  namespace: {{ $namespace }}
spec:
  serviceName: debezium-service
  selector:
    matchLabels:
      app: debezium
  template:
    metadata:
      labels:
        app: debezium
    spec:
      containers:
        - name: debezium-container
          image: {{ .image }}
          ports:
            - containerPort: {{ .port }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                  configMapKeyRef:
                    name: {{ $.Values.global.infrastructureConfigMapName }}
                    key: KAFKA_BOOTSTRAP_SERVERS
            - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.infrastructureConfigMapName }}
                  key: SCHEMA_REGISTRY_HOST
            - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.infrastructureConfigMapName }}
                  key: SCHEMA_REGISTRY_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: debezium-service
  namespace: {{ $namespace }}
spec:
  selector:
    app: debezium
  ports:
    - protocol: TCP
      port: {{ .port }}
{{- end }}