name: Test gcloud

on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build with Maven
      run: > 
        pwd;
