name: Test gcloud

on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup docker credentials gcr
      run: > 
        curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.1.22%7D/docker-credential-gcr_linux_amd64-2.1.22.tar.gz" \
        | tar xz docker-credential-gcr \
        && chmod +x docker-credential-gcr && sudo mv docker-credential-gcr /usr/bin;
        docker-credential-gcr configure-docker --registries=${{ secrets.GCP_ARTIFACT_REGISTRY }};
        echo