name: Test gcloud

on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI, install plugin'
      run: >
        gcloud info;
        gcloud components install gke-gcloud-auth-plugin;

    - name: 'Connect to cluster'
      run: >
        gcloud container clusters get-credentials my-first-cluster-1 --zone us-east1-b --project the-delight-409622;
        kubectl get pods;
        helm list;
        ls;