
name: GCP Build maven project, push images into Artifact Registry

on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven, create docker images
      run: > 
        cd /home/runner/work/social-media-feed/social-media-feed/social-media-feed-backend;
        mvn clean install;
    - name: Build Debezium image
      run: >
        cd /home/runner/work/social-media-feed/social-media-feed/social-media-feed-backend/deployment/docker-compose;
        docker build -t com.social.media.feed/debezium-connect:1.0-SNAPSHOT -f ./debezium.dockerfile .
    - name: Log images
      run: docker image ls