
name: GCP Build maven project, push images into Artifact Registry

on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Build project
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven, create docker images
      run: > 
        cd /home/runner/work/social-media-feed/social-media-feed/social-media-feed-backend;
        mvn clean install;
    - name: Build Debezium image
      run: >
        cd /home/runner/work/social-media-feed/social-media-feed/social-media-feed-backend/deployment/docker-compose;
        docker build -t com.social.media.feed/debezium-connect:1.0-SNAPSHOT -f ./debezium.dockerfile .
    - name: Log images
      run: docker image ls | grep com.social
    
    # GCP Stuff
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: 'Push images'
      run: >
        echo "${{ secrets.GCP_ARTIFACT_REGISTRY }}";

        docker tag -t com.social.media.feed/account-service:1.0-SNAPSHOT "${{ secrets.GCP_ARTIFACT_REGISTRY }}/account-service:1.0-SNAPSHOT";
        docker push "${{ secrets.GCP_ARTIFACT_REGISTRY }}/account-service:1.0-SNAPSHOT";

        docker tag -t com.social.media.feed/post-service:1.0-SNAPSHOT "${{ secrets.GCP_ARTIFACT_REGISTRY }}/post-service:1.0-SNAPSHOT";
        docker push "${{ secrets.GCP_ARTIFACT_REGISTRY }}/post-service:1.0-SNAPSHOT";

        docker tag -t com.social.media.feed/feed-service:1.0-SNAPSHOT "${{ secrets.GCP_ARTIFACT_REGISTRY }}/feed-service:1.0-SNAPSHOT";
        docker push "${{ secrets.GCP_ARTIFACT_REGISTRY }}/feed-service:1.0-SNAPSHOT";

        docker tag -t com.social.media.feed/api-gateway-service:1.0-SNAPSHOT "${{ secrets.GCP_ARTIFACT_REGISTRY }}/api-gateway-service:1.0-SNAPSHOT";
        docker push "${{ secrets.GCP_ARTIFACT_REGISTRY }}/api-gateway-service:1.0-SNAPSHOT";

        docker tag -t com.social.media.feed/eureka-service:1.0-SNAPSHOT "${{ secrets.GCP_ARTIFACT_REGISTRY }}/eureka-service:1.0-SNAPSHOT";
        docker push "${{ secrets.GCP_ARTIFACT_REGISTRY }}/eureka-service:1.0-SNAPSHOT";

        docker tag -t com.social.media.feed/debezium-connect:1.0-SNAPSHOT "${{ secrets.GCP_ARTIFACT_REGISTRY }}/debezium-connect:1.0-SNAPSHOT";
        docker push "${{ secrets.GCP_ARTIFACT_REGISTRY }}/debezium-connect:1.0-SNAPSHOT";