
name: GCP Build maven project, push images into Artifact Registry

on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Build project
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    # Build Spring project, run integration tests, create images of microservices
    - name: Build with Maven, create docker images
      run: > 
        cd /home/runner/work/social-media-feed/social-media-feed/social-media-feed-backend;
        mvn clean install;
    # Builds an image of Debezium that is compatible with Confluent Schema Registry
    - name: Build Debezium image
      run: >
        cd /home/runner/work/social-media-feed/social-media-feed/social-media-feed-backend/deployment/docker-compose;
        docker build -t com.social.media.feed/debezium-connect:1.0-SNAPSHOT -f ./debezium.dockerfile .
    # Logs images
    - name: Log images
      run: docker image ls | grep com.social
    
    # GCP Authentication
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: 'Use gcloud CLI'
      run: >
        gcloud info;
        gcloud auth configure-docker us-east1-docker.pkg.dev;
        gcloud components install gke-gcloud-auth-plugin;

    # Push images to registry
    - name: 'Push images'
      run: >
        docker tag com.social.media.feed/account-service:1.0-SNAPSHOT "${{ secrets.GCP_ARTIFACT_REGISTRY }}/account-service:latest";
        docker push "${{ secrets.GCP_ARTIFACT_REGISTRY }}/account-service:latest";

        docker tag com.social.media.feed/post-service:1.0-SNAPSHOT "${{ secrets.GCP_ARTIFACT_REGISTRY }}/post-service:latest";
        docker push "${{ secrets.GCP_ARTIFACT_REGISTRY }}/post-service:latest";

        docker tag com.social.media.feed/feed-service:1.0-SNAPSHOT "${{ secrets.GCP_ARTIFACT_REGISTRY }}/feed-service:latest";
        docker push "${{ secrets.GCP_ARTIFACT_REGISTRY }}/feed-service:latest";

        docker tag com.social.media.feed/api-gateway-service:1.0-SNAPSHOT "${{ secrets.GCP_ARTIFACT_REGISTRY }}/api-gateway-service:latest";
        docker push "${{ secrets.GCP_ARTIFACT_REGISTRY }}/api-gateway-service:latest";

        docker tag com.social.media.feed/eureka-service:1.0-SNAPSHOT "${{ secrets.GCP_ARTIFACT_REGISTRY }}/eureka-service:latest";
        docker push "${{ secrets.GCP_ARTIFACT_REGISTRY }}/eureka-service:latest";

        docker tag com.social.media.feed/debezium-connect:1.0-SNAPSHOT "${{ secrets.GCP_ARTIFACT_REGISTRY }}/debezium-connect:latest";
        docker push "${{ secrets.GCP_ARTIFACT_REGISTRY }}/debezium-connect:latest";
    
    - name: 'Update deployment'
      run: >
        gcloud container clusters get-credentials my-first-cluster-1 --zone us-east1-b --project the-delight-409622;
        